// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const createComment = `-- name: CreateComment :execresult

INSERT INTO comments (post_id, user_id, body) VALUES (?, ?, ?)
`

type CreateCommentParams struct {
	PostID uint64
	UserID uint64
	Body   string
}

// コメント。返信ツリーは作らないため親への参照は持たない。
func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createComment, arg.PostID, arg.UserID, arg.Body)
}

const decrementCommentCount = `-- name: DecrementCommentCount :exec
UPDATE posts SET comment_count = comment_count - 1 WHERE id = ? AND comment_count > 0
`

func (q *Queries) DecrementCommentCount(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, decrementCommentCount, id)
	return err
}

const deleteCommentByID = `-- name: DeleteCommentByID :execresult
DELETE FROM comments WHERE id = ?
`

func (q *Queries) DeleteCommentByID(ctx context.Context, id uint64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteCommentByID, id)
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT c.id, c.post_id, c.user_id, c.body, c.created_at,
       u.handle, u.display_name, u.bio
FROM comments c
JOIN users u ON u.id = c.user_id
WHERE c.id = ?
`

type GetCommentByIDRow struct {
	ID          uint64
	PostID      uint64
	UserID      uint64
	Body        string
	CreatedAt   time.Time
	Handle      string
	DisplayName string
	Bio         sql.NullString
}

func (q *Queries) GetCommentByID(ctx context.Context, id uint64) (GetCommentByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCommentByID, id)
	var i GetCommentByIDRow
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.Handle,
		&i.DisplayName,
		&i.Bio,
	)
	return i, err
}

const incrementCommentCount = `-- name: IncrementCommentCount :exec
UPDATE posts SET comment_count = comment_count + 1 WHERE id = ?
`

func (q *Queries) IncrementCommentCount(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, incrementCommentCount, id)
	return err
}

const listCommentsAfter = `-- name: ListCommentsAfter :many
SELECT c.id, c.post_id, c.user_id, c.body, c.created_at,
       u.handle, u.display_name, u.bio
FROM comments c
JOIN users u ON u.id = c.user_id
WHERE c.post_id = ? AND c.id > ?
ORDER BY c.id
LIMIT ?
`

type ListCommentsAfterParams struct {
	PostID uint64
	ID     uint64
	Limit  int32
}

type ListCommentsAfterRow struct {
	ID          uint64
	PostID      uint64
	UserID      uint64
	Body        string
	CreatedAt   time.Time
	Handle      string
	DisplayName string
	Bio         sql.NullString
}

// 古い順に返す。会話は上から読むものであり、
// フィードのように新しいものから見るのは適さない。
//
// カーソルは id のみでよい。created_at はデータベースが挿入時に付けており
// AUTO_INCREMENT と同じ順序になるためである。
// 索引 ix_comments_post (post_id, id) が効く。
//
// **2列目が created_at だった頃は効いていなかった。** post_id で絞った
// あとの並びが created_at → id になり、id の範囲を索引で辿れないため、
// MySQL は PRIMARY を id > ? で範囲走査して post_id を捨てる計画を選ぶ。
// 並べ替えは出ないので Extra だけを見ていると気づけない（000009 で置換）。
func (q *Queries) ListCommentsAfter(ctx context.Context, arg ListCommentsAfterParams) ([]ListCommentsAfterRow, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsAfter, arg.PostID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentsAfterRow{}
	for rows.Next() {
		var i ListCommentsAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.UserID,
			&i.Body,
			&i.CreatedAt,
			&i.Handle,
			&i.DisplayName,
			&i.Bio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
