// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: follows.sql

package dbgen

import (
	"context"
	"database/sql"
	"strings"
)

const countFollowers = `-- name: CountFollowers :one
SELECT COUNT(*) FROM follows WHERE followee_id = ?
`

func (q *Queries) CountFollowers(ctx context.Context, followeeID uint64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFollowers, followeeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFollowing = `-- name: CountFollowing :one
SELECT COUNT(*) FROM follows WHERE follower_id = ?
`

func (q *Queries) CountFollowing(ctx context.Context, followerID uint64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFollowing, followerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteFollow = `-- name: DeleteFollow :execresult
DELETE FROM follows WHERE follower_id = ? AND followee_id = ?
`

type DeleteFollowParams struct {
	FollowerID uint64
	FolloweeID uint64
}

func (q *Queries) DeleteFollow(ctx context.Context, arg DeleteFollowParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteFollow, arg.FollowerID, arg.FolloweeID)
}

const insertFollow = `-- name: InsertFollow :execresult

INSERT IGNORE INTO follows (follower_id, followee_id) VALUES (?, ?)
`

type InsertFollowParams struct {
	FollowerID uint64
	FolloweeID uint64
}

// フォロー。
//
// 主キーは (follower_id, followee_id)。追加の索引が
// ix_follows_followee (followee_id, follower_id)。
// 「自分がフォローしている人」と「自分をフォローしている人」の両方向を
// それぞれ索引だけで引けるようにしてある。
// INSERT IGNORE により、既にフォローしていても失敗しない（冪等）。
// RowsAffected が 0 なら「既にあった」であり、通知を二重に作らずに済む。
func (q *Queries) InsertFollow(ctx context.Context, arg InsertFollowParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertFollow, arg.FollowerID, arg.FolloweeID)
}

const isFollowing = `-- name: IsFollowing :one
SELECT EXISTS(
    SELECT 1 FROM follows WHERE follower_id = ? AND followee_id = ?
)
`

type IsFollowingParams struct {
	FollowerID uint64
	FolloweeID uint64
}

func (q *Queries) IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isFollowing, arg.FollowerID, arg.FolloweeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listFollowedUserIDs = `-- name: ListFollowedUserIDs :many
SELECT followee_id FROM follows
WHERE follower_id = ? AND followee_id IN (/*SLICE:user_ids*/?)
`

type ListFollowedUserIDsParams struct {
	FollowerID uint64
	UserIds    []uint64
}

// 一覧に並んだ相手のうち、閲覧者がフォローしているのはどれか。
//
// **一覧の1件ごとに問い合わせない。** 50件返す画面で50回の往復になる。
// いいねの ListLikedPostIDs と同じ考え方である。
func (q *Queries) ListFollowedUserIDs(ctx context.Context, arg ListFollowedUserIDsParams) ([]uint64, error) {
	query := listFollowedUserIDs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.FollowerID)
	if len(arg.UserIds) > 0 {
		for _, v := range arg.UserIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:user_ids*/?", strings.Repeat(",?", len(arg.UserIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:user_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uint64{}
	for rows.Next() {
		var followee_id uint64
		if err := rows.Scan(&followee_id); err != nil {
			return nil, err
		}
		items = append(items, followee_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowersAfter = `-- name: ListFollowersAfter :many
SELECT u.id, u.handle, u.display_name, u.bio
FROM follows f
JOIN users u ON u.id = f.follower_id
WHERE f.followee_id = ? AND f.follower_id > ? AND u.deleted_at IS NULL
ORDER BY f.follower_id
LIMIT ?
`

type ListFollowersAfterParams struct {
	FolloweeID uint64
	FollowerID uint64
	Limit      int32
}

type ListFollowersAfterRow struct {
	ID          uint64
	Handle      string
	DisplayName string
	Bio         sql.NullString
}

// フォロワーの一覧。
//
// カーソルは利用者 id の昇順である。索引が (followee_id, follower_id) なので、
// この順でのみ索引だけで続きから取れる。フォローした日時順にするなら
// created_at を含む索引を足す必要がある。
func (q *Queries) ListFollowersAfter(ctx context.Context, arg ListFollowersAfterParams) ([]ListFollowersAfterRow, error) {
	rows, err := q.db.QueryContext(ctx, listFollowersAfter, arg.FolloweeID, arg.FollowerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowersAfterRow{}
	for rows.Next() {
		var i ListFollowersAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.Handle,
			&i.DisplayName,
			&i.Bio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowingAfter = `-- name: ListFollowingAfter :many
SELECT u.id, u.handle, u.display_name, u.bio
FROM follows f
JOIN users u ON u.id = f.followee_id
WHERE f.follower_id = ? AND f.followee_id > ? AND u.deleted_at IS NULL
ORDER BY f.followee_id
LIMIT ?
`

type ListFollowingAfterParams struct {
	FollowerID uint64
	FolloweeID uint64
	Limit      int32
}

type ListFollowingAfterRow struct {
	ID          uint64
	Handle      string
	DisplayName string
	Bio         sql.NullString
}

// フォロー中の一覧。こちらは主キー (follower_id, followee_id) が効く。
func (q *Queries) ListFollowingAfter(ctx context.Context, arg ListFollowingAfterParams) ([]ListFollowingAfterRow, error) {
	rows, err := q.db.QueryContext(ctx, listFollowingAfter, arg.FollowerID, arg.FolloweeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowingAfterRow{}
	for rows.Next() {
		var i ListFollowingAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.Handle,
			&i.DisplayName,
			&i.Bio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
