// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: likes.sql

package dbgen

import (
	"context"
	"database/sql"
	"strings"
)

const decrementLikeCount = `-- name: DecrementLikeCount :exec
UPDATE posts SET like_count = like_count - 1 WHERE id = ? AND like_count > 0
`

// カウンタが負にならないようにする。
// 万一ずれても 0 未満にはしない（UNSIGNED なので負にすると桁あふれする）。
func (q *Queries) DecrementLikeCount(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, decrementLikeCount, id)
	return err
}

const deleteLike = `-- name: DeleteLike :execresult
DELETE FROM likes WHERE user_id = ? AND post_id = ?
`

type DeleteLikeParams struct {
	UserID uint64
	PostID uint64
}

func (q *Queries) DeleteLike(ctx context.Context, arg DeleteLikeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteLike, arg.UserID, arg.PostID)
}

const incrementLikeCount = `-- name: IncrementLikeCount :exec
UPDATE posts SET like_count = like_count + 1 WHERE id = ?
`

func (q *Queries) IncrementLikeCount(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, incrementLikeCount, id)
	return err
}

const insertLike = `-- name: InsertLike :execresult

INSERT IGNORE INTO likes (user_id, post_id) VALUES (?, ?)
`

type InsertLikeParams struct {
	UserID uint64
	PostID uint64
}

// いいね。
//
// 主キーの列順が (user_id, post_id) であることに意味がある。
// フィードでは「表示する20件のうち自分がいいね済みなのはどれか」を
// WHERE user_id = ? AND post_id IN (...) で求めるため、この順でないと効かない。
// 冪等にする。既にあれば何もしない。
// **更新件数で「新しく入ったか」を判定し、カウンタの増減に使う。**
// 事前に SELECT で確認すると、確認と INSERT の間に割り込まれる余地が残る。
func (q *Queries) InsertLike(ctx context.Context, arg InsertLikeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertLike, arg.UserID, arg.PostID)
}

const isPostLiked = `-- name: IsPostLiked :one
SELECT EXISTS(SELECT 1 FROM likes WHERE user_id = ? AND post_id = ?) AS liked
`

type IsPostLikedParams struct {
	UserID uint64
	PostID uint64
}

func (q *Queries) IsPostLiked(ctx context.Context, arg IsPostLikedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isPostLiked, arg.UserID, arg.PostID)
	var liked bool
	err := row.Scan(&liked)
	return liked, err
}

const listLikedPostIDs = `-- name: ListLikedPostIDs :many
SELECT post_id FROM likes
WHERE user_id = ? AND post_id IN (/*SLICE:post_ids*/?)
`

type ListLikedPostIDsParams struct {
	UserID  uint64
	PostIds []uint64
}

// フィード用。**投稿ごとに問い合わせない。**
func (q *Queries) ListLikedPostIDs(ctx context.Context, arg ListLikedPostIDsParams) ([]uint64, error) {
	query := listLikedPostIDs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UserID)
	if len(arg.PostIds) > 0 {
		for _, v := range arg.PostIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:post_ids*/?", strings.Repeat(",?", len(arg.PostIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:post_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uint64{}
	for rows.Next() {
		var post_id uint64
		if err := rows.Scan(&post_id); err != nil {
			return nil, err
		}
		items = append(items, post_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
