// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package dbgen

import (
	"context"
	"database/sql"
	"strings"
)

const attachMediaToPost = `-- name: AttachMediaToPost :execresult
UPDATE media
SET post_id = ?, sort_order = ?
WHERE id = ?
  AND user_id = ?
  AND post_id IS NULL
  AND status = 'processed'
`

type AttachMediaToPostParams struct {
	PostID    sql.NullInt64
	SortOrder uint8
	ID        uint64
	UserID    uint64
}

// 投稿に紐づける。
//
// 条件が要点である。**自分のもので、処理が完了しており、まだどの投稿にも
// 属していない**画像だけを紐づける。条件に合わなければ更新件数が 0 になり、
// 呼び出し側がそれを検出する。SELECT で確認してから UPDATE すると、
// その間に別のリクエストが同じ画像を使う余地が残る。
func (q *Queries) AttachMediaToPost(ctx context.Context, arg AttachMediaToPostParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, attachMediaToPost,
		arg.PostID,
		arg.SortOrder,
		arg.ID,
		arg.UserID,
	)
}

const createMediaVariant = `-- name: CreateMediaVariant :exec
INSERT INTO media_variants (media_id, kind, s3_key, width, height, bytes)
VALUES (?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE s3_key = VALUES(s3_key), width = VALUES(width), height = VALUES(height), bytes = VALUES(bytes)
`

type CreateMediaVariantParams struct {
	MediaID uint64
	Kind    MediaVariantsKind
	S3Key   string
	Width   uint32
	Height  uint32
	Bytes   uint32
}

func (q *Queries) CreateMediaVariant(ctx context.Context, arg CreateMediaVariantParams) error {
	_, err := q.db.ExecContext(ctx, createMediaVariant,
		arg.MediaID,
		arg.Kind,
		arg.S3Key,
		arg.Width,
		arg.Height,
		arg.Bytes,
	)
	return err
}

const createPendingMedia = `-- name: CreatePendingMedia :execresult

INSERT INTO media (user_id, s3_key, status)
VALUES (?, ?, 'pending')
`

type CreatePendingMediaParams struct {
	UserID uint64
	S3Key  string
}

// 画像。status が「アップロードされる予定」を表す状態機械になっている。
// 署名付きURLを発行する時点で pending として先に記録する（write-ahead）。
// これが無いと、送信後に投稿が確定されなかったオブジェクトを後から特定できない。
func (q *Queries) CreatePendingMedia(ctx context.Context, arg CreatePendingMediaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPendingMedia, arg.UserID, arg.S3Key)
}

const getMediaByID = `-- name: GetMediaByID :one
SELECT id, user_id, post_id, s3_key, mime, width, height, bytes, sort_order, status
FROM media
WHERE id = ?
`

type GetMediaByIDRow struct {
	ID        uint64
	UserID    uint64
	PostID    sql.NullInt64
	S3Key     string
	Mime      sql.NullString
	Width     sql.NullInt32
	Height    sql.NullInt32
	Bytes     sql.NullInt32
	SortOrder uint8
	Status    MediaStatus
}

func (q *Queries) GetMediaByID(ctx context.Context, id uint64) (GetMediaByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMediaByID, id)
	var i GetMediaByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PostID,
		&i.S3Key,
		&i.Mime,
		&i.Width,
		&i.Height,
		&i.Bytes,
		&i.SortOrder,
		&i.Status,
	)
	return i, err
}

const getMediaByS3Key = `-- name: GetMediaByS3Key :one
SELECT id, user_id, post_id, s3_key, mime, width, height, bytes, sort_order, status
FROM media
WHERE s3_key = ?
`

type GetMediaByS3KeyRow struct {
	ID        uint64
	UserID    uint64
	PostID    sql.NullInt64
	S3Key     string
	Mime      sql.NullString
	Width     sql.NullInt32
	Height    sql.NullInt32
	Bytes     sql.NullInt32
	SortOrder uint8
	Status    MediaStatus
}

func (q *Queries) GetMediaByS3Key(ctx context.Context, s3Key string) (GetMediaByS3KeyRow, error) {
	row := q.db.QueryRowContext(ctx, getMediaByS3Key, s3Key)
	var i GetMediaByS3KeyRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PostID,
		&i.S3Key,
		&i.Mime,
		&i.Width,
		&i.Height,
		&i.Bytes,
		&i.SortOrder,
		&i.Status,
	)
	return i, err
}

const listMediaByPostID = `-- name: ListMediaByPostID :many
SELECT id, post_id, width, height, s3_key
FROM media
WHERE post_id = ?
ORDER BY sort_order, id
`

type ListMediaByPostIDRow struct {
	ID     uint64
	PostID sql.NullInt64
	Width  sql.NullInt32
	Height sql.NullInt32
	S3Key  string
}

func (q *Queries) ListMediaByPostID(ctx context.Context, postID sql.NullInt64) ([]ListMediaByPostIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listMediaByPostID, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMediaByPostIDRow{}
	for rows.Next() {
		var i ListMediaByPostIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.Width,
			&i.Height,
			&i.S3Key,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaByPostIDs = `-- name: ListMediaByPostIDs :many
SELECT id, post_id, width, height, s3_key
FROM media
WHERE post_id IN (/*SLICE:post_ids*/?)
ORDER BY post_id, sort_order, id
`

type ListMediaByPostIDsRow struct {
	ID     uint64
	PostID sql.NullInt64
	Width  sql.NullInt32
	Height sql.NullInt32
	S3Key  string
}

// 複数の投稿の画像をまとめて取る。
//
// **投稿ごとに問い合わせない（N+1 を作らない）。** フィードは1画面で
// 20件返すため、投稿ごとに画像を引くと 20 回の往復になる。
func (q *Queries) ListMediaByPostIDs(ctx context.Context, postIds []sql.NullInt64) ([]ListMediaByPostIDsRow, error) {
	query := listMediaByPostIDs
	var queryParams []interface{}
	if len(postIds) > 0 {
		for _, v := range postIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:post_ids*/?", strings.Repeat(",?", len(postIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:post_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMediaByPostIDsRow{}
	for rows.Next() {
		var i ListMediaByPostIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.Width,
			&i.Height,
			&i.S3Key,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaKeysByPostID = `-- name: ListMediaKeysByPostID :many
SELECT m.s3_key AS s3_key
FROM media m
WHERE m.post_id = ?
UNION ALL
SELECT v.s3_key AS s3_key
FROM media_variants v
JOIN media m2 ON m2.id = v.media_id
WHERE m2.post_id = ?
`

type ListMediaKeysByPostIDParams struct {
	PostID   sql.NullInt64
	PostID_2 sql.NullInt64
}

// 削除時に S3 のオブジェクトも消すため、キーを集める。
// 外部キーの連鎖削除では S3 上の実体は消えない。
func (q *Queries) ListMediaKeysByPostID(ctx context.Context, arg ListMediaKeysByPostIDParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listMediaKeysByPostID, arg.PostID, arg.PostID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var s3_key string
		if err := rows.Scan(&s3_key); err != nil {
			return nil, err
		}
		items = append(items, s3_key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantsByPostID = `-- name: ListVariantsByPostID :many
SELECT v.media_id, v.kind, v.s3_key, v.width, v.height
FROM media_variants v
JOIN media m ON m.id = v.media_id
WHERE m.post_id = ?
`

type ListVariantsByPostIDRow struct {
	MediaID uint64
	Kind    MediaVariantsKind
	S3Key   string
	Width   uint32
	Height  uint32
}

func (q *Queries) ListVariantsByPostID(ctx context.Context, postID sql.NullInt64) ([]ListVariantsByPostIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listVariantsByPostID, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVariantsByPostIDRow{}
	for rows.Next() {
		var i ListVariantsByPostIDRow
		if err := rows.Scan(
			&i.MediaID,
			&i.Kind,
			&i.S3Key,
			&i.Width,
			&i.Height,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantsByPostIDs = `-- name: ListVariantsByPostIDs :many
SELECT v.media_id, m.post_id, v.kind, v.s3_key, v.width, v.height
FROM media_variants v
JOIN media m ON m.id = v.media_id
WHERE m.post_id IN (/*SLICE:post_ids*/?)
`

type ListVariantsByPostIDsRow struct {
	MediaID uint64
	PostID  sql.NullInt64
	Kind    MediaVariantsKind
	S3Key   string
	Width   uint32
	Height  uint32
}

func (q *Queries) ListVariantsByPostIDs(ctx context.Context, postIds []sql.NullInt64) ([]ListVariantsByPostIDsRow, error) {
	query := listVariantsByPostIDs
	var queryParams []interface{}
	if len(postIds) > 0 {
		for _, v := range postIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:post_ids*/?", strings.Repeat(",?", len(postIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:post_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVariantsByPostIDsRow{}
	for rows.Next() {
		var i ListVariantsByPostIDsRow
		if err := rows.Scan(
			&i.MediaID,
			&i.PostID,
			&i.Kind,
			&i.S3Key,
			&i.Width,
			&i.Height,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMediaFailed = `-- name: MarkMediaFailed :exec
UPDATE media
SET status = 'failed'
WHERE id = ?
`

func (q *Queries) MarkMediaFailed(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, markMediaFailed, id)
	return err
}

const markMediaProcessed = `-- name: MarkMediaProcessed :exec
UPDATE media
SET status = 'processed', mime = ?, width = ?, height = ?, bytes = ?
WHERE id = ?
`

type MarkMediaProcessedParams struct {
	Mime   sql.NullString
	Width  sql.NullInt32
	Height sql.NullInt32
	Bytes  sql.NullInt32
	ID     uint64
}

// 画像処理の完了。
func (q *Queries) MarkMediaProcessed(ctx context.Context, arg MarkMediaProcessedParams) error {
	_, err := q.db.ExecContext(ctx, markMediaProcessed,
		arg.Mime,
		arg.Width,
		arg.Height,
		arg.Bytes,
		arg.ID,
	)
	return err
}
