// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type MediaStatus string

const (
	MediaStatusPending   MediaStatus = "pending"
	MediaStatusUploaded  MediaStatus = "uploaded"
	MediaStatusProcessed MediaStatus = "processed"
	MediaStatusFailed    MediaStatus = "failed"
)

func (e *MediaStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MediaStatus(s)
	case string:
		*e = MediaStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MediaStatus: %T", src)
	}
	return nil
}

type NullMediaStatus struct {
	MediaStatus MediaStatus
	Valid       bool // Valid is true if MediaStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMediaStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MediaStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MediaStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMediaStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MediaStatus), nil
}

type MediaVariantsKind string

const (
	MediaVariantsKindThumb    MediaVariantsKind = "thumb"
	MediaVariantsKindMedium   MediaVariantsKind = "medium"
	MediaVariantsKindOriginal MediaVariantsKind = "original"
)

func (e *MediaVariantsKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MediaVariantsKind(s)
	case string:
		*e = MediaVariantsKind(s)
	default:
		return fmt.Errorf("unsupported scan type for MediaVariantsKind: %T", src)
	}
	return nil
}

type NullMediaVariantsKind struct {
	MediaVariantsKind MediaVariantsKind
	Valid             bool // Valid is true if MediaVariantsKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMediaVariantsKind) Scan(value interface{}) error {
	if value == nil {
		ns.MediaVariantsKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MediaVariantsKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMediaVariantsKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MediaVariantsKind), nil
}

type NotificationsType string

const (
	NotificationsTypeLike    NotificationsType = "like"
	NotificationsTypeComment NotificationsType = "comment"
	NotificationsTypeFollow  NotificationsType = "follow"
)

func (e *NotificationsType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationsType(s)
	case string:
		*e = NotificationsType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationsType: %T", src)
	}
	return nil
}

type NullNotificationsType struct {
	NotificationsType NotificationsType
	Valid             bool // Valid is true if NotificationsType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationsType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationsType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationsType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationsType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationsType), nil
}

type Comment struct {
	ID        uint64
	PostID    uint64
	UserID    uint64
	Body      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Follow struct {
	FollowerID uint64
	FolloweeID uint64
	CreatedAt  time.Time
}

type Like struct {
	UserID    uint64
	PostID    uint64
	CreatedAt time.Time
}

type Media struct {
	ID        uint64
	UserID    uint64
	PostID    sql.NullInt64
	S3Key     string
	Mime      sql.NullString
	Width     sql.NullInt32
	Height    sql.NullInt32
	Bytes     sql.NullInt32
	AltText   sql.NullString
	SortOrder uint8
	Status    MediaStatus
	CreatedAt time.Time
	UpdatedAt time.Time
}

type MediaVariant struct {
	ID        uint64
	MediaID   uint64
	Kind      MediaVariantsKind
	S3Key     string
	Width     uint32
	Height    uint32
	Bytes     uint32
	CreatedAt time.Time
}

type Notification struct {
	ID          uint64
	UserID      uint64
	ActorID     uint64
	Type        NotificationsType
	PostID      sql.NullInt64
	CommentID   sql.NullInt64
	ReadAt      sql.NullTime
	DeliveredAt sql.NullTime
	CreatedAt   time.Time
}

type Post struct {
	ID             uint64
	UserID         uint64
	Body           string
	PrefectureCode string
	SpotName       sql.NullString
	VisitedOn      time.Time
	LikeCount      uint32
	CommentCount   uint32
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type PostTag struct {
	PostID uint64
	TagID  uint64
}

type Prefecture struct {
	Code      string
	Name      string
	NameKana  string
	Region    string
	SortOrder int16
}

type RefreshToken struct {
	ID         uint64
	UserID     uint64
	TokenHash  string
	ExpiresAt  time.Time
	RevokedAt  sql.NullTime
	ReplacedBy sql.NullInt64
	CreatedAt  time.Time
}

type Tag struct {
	ID        uint64
	Name      string
	CreatedAt time.Time
}

type User struct {
	ID            uint64
	Handle        string
	Email         string
	PasswordHash  string
	DisplayName   string
	Bio           sql.NullString
	AvatarMediaID sql.NullInt64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     sql.NullTime
}
