// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createNotification = `-- name: CreateNotification :exec

INSERT INTO notifications (user_id, actor_id, type, post_id, comment_id)
VALUES (?, ?, ?, ?, ?)
`

type CreateNotificationParams struct {
	UserID    uint64
	ActorID   uint64
	Type      NotificationsType
	PostID    sql.NullInt64
	CommentID sql.NullInt64
}

// 通知。
//
// **契機となる操作（いいね・コメント・フォロー）と同一トランザクションで
// INSERT する。** キューや Outbox は使わない。「いいねは記録されたが
// 通知が消えた」状態を作らないための最も単純な方法である。
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) error {
	_, err := q.db.ExecContext(ctx, createNotification,
		arg.UserID,
		arg.ActorID,
		arg.Type,
		arg.PostID,
		arg.CommentID,
	)
	return err
}

const deleteFollowNotification = `-- name: DeleteFollowNotification :exec
DELETE FROM notifications
WHERE user_id = ? AND actor_id = ? AND type = 'follow'
`

type DeleteFollowNotificationParams struct {
	UserID  uint64
	ActorID uint64
}

func (q *Queries) DeleteFollowNotification(ctx context.Context, arg DeleteFollowNotificationParams) error {
	_, err := q.db.ExecContext(ctx, deleteFollowNotification, arg.UserID, arg.ActorID)
	return err
}

const deleteLikeNotification = `-- name: DeleteLikeNotification :exec
DELETE FROM notifications
WHERE user_id = ? AND actor_id = ? AND type = 'like' AND post_id = ?
`

type DeleteLikeNotificationParams struct {
	UserID  uint64
	ActorID uint64
	PostID  sql.NullInt64
}

// いいねを取り消したときに、対応する通知も消す。
// 残すと「いいねされた」通知だけが宙に浮く。
func (q *Queries) DeleteLikeNotification(ctx context.Context, arg DeleteLikeNotificationParams) error {
	_, err := q.db.ExecContext(ctx, deleteLikeNotification, arg.UserID, arg.ActorID, arg.PostID)
	return err
}
