// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const createPost = `-- name: CreatePost :execresult

INSERT INTO posts (user_id, body, prefecture_code, spot_name, visited_on)
VALUES (?, ?, ?, ?, ?)
`

type CreatePostParams struct {
	UserID         uint64
	Body           string
	PrefectureCode string
	SpotName       sql.NullString
	VisitedOn      time.Time
}

// 投稿。
func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPost,
		arg.UserID,
		arg.Body,
		arg.PrefectureCode,
		arg.SpotName,
		arg.VisitedOn,
	)
}

const deletePost = `-- name: DeletePost :execresult
DELETE FROM posts
WHERE id = ? AND user_id = ?
`

type DeletePostParams struct {
	ID     uint64
	UserID uint64
}

func (q *Queries) DeletePost(ctx context.Context, arg DeletePostParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deletePost, arg.ID, arg.UserID)
}

const getPostByID = `-- name: GetPostByID :one
SELECT
    p.id, p.user_id, p.body, p.prefecture_code, p.spot_name, p.visited_on,
    p.like_count, p.comment_count, p.created_at, p.updated_at,
    u.handle, u.display_name, u.bio,
    pref.name AS prefecture_name, pref.name_kana AS prefecture_name_kana, pref.region
FROM posts p
JOIN users u ON u.id = p.user_id
JOIN prefectures pref ON pref.code = p.prefecture_code
WHERE p.id = ?
`

type GetPostByIDRow struct {
	ID                 uint64
	UserID             uint64
	Body               string
	PrefectureCode     string
	SpotName           sql.NullString
	VisitedOn          time.Time
	LikeCount          uint32
	CommentCount       uint32
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Handle             string
	DisplayName        string
	Bio                sql.NullString
	PrefectureName     string
	PrefectureNameKana string
	Region             string
}

func (q *Queries) GetPostByID(ctx context.Context, id uint64) (GetPostByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPostByID, id)
	var i GetPostByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Body,
		&i.PrefectureCode,
		&i.SpotName,
		&i.VisitedOn,
		&i.LikeCount,
		&i.CommentCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Handle,
		&i.DisplayName,
		&i.Bio,
		&i.PrefectureName,
		&i.PrefectureNameKana,
		&i.Region,
	)
	return i, err
}

const getPostOwner = `-- name: GetPostOwner :one
SELECT user_id FROM posts WHERE id = ?
`

// 投稿の所有者だけを取る。権限確認のために本体を全部読む必要はない。
func (q *Queries) GetPostOwner(ctx context.Context, id uint64) (uint64, error) {
	row := q.db.QueryRowContext(ctx, getPostOwner, id)
	var user_id uint64
	err := row.Scan(&user_id)
	return user_id, err
}

const listFollowingFeedBefore = `-- name: ListFollowingFeedBefore :many
SELECT
    p.id, p.user_id, p.body, p.prefecture_code, p.spot_name, p.visited_on,
    p.like_count, p.comment_count, p.created_at, p.updated_at,
    u.handle, u.display_name, u.bio,
    pref.name AS prefecture_name, pref.name_kana AS prefecture_name_kana, pref.region
FROM posts p
JOIN follows f ON f.followee_id = p.user_id AND f.follower_id = ?
JOIN users u ON u.id = p.user_id
JOIN prefectures pref ON pref.code = p.prefecture_code
WHERE p.id < ?
ORDER BY p.id DESC
LIMIT ?
`

type ListFollowingFeedBeforeParams struct {
	FollowerID uint64
	ID         uint64
	Limit      int32
}

type ListFollowingFeedBeforeRow struct {
	ID                 uint64
	UserID             uint64
	Body               string
	PrefectureCode     string
	SpotName           sql.NullString
	VisitedOn          time.Time
	LikeCount          uint32
	CommentCount       uint32
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Handle             string
	DisplayName        string
	Bio                sql.NullString
	PrefectureName     string
	PrefectureNameKana string
	Region             string
}

// フォロー中フィード。
//
// **IN (SELECT ...) ではなく follows との JOIN で書く。**
// 意味は同じだが、MySQL は JOIN のほうが結合順を選べる。
//
// **ここは負荷試験の対象である。** 想定は1人あたり平均200フォロー。
// フォロー先は follows の主キー (follower_id, followee_id) で引けるが、
// **全体を id 順に並べる部分は索引で解決できない。**
// EXPLAIN に Using temporary; Using filesort が出る（2026-08-29 に実測）。
// 複数の利用者の投稿を1つの順序に混ぜる以上、索引1本では避けられない。
// 実測して厳しければ、フィードを事前に組み立てて持つ形（fan-out）へ
// 作り方ごと変える判断になる。
func (q *Queries) ListFollowingFeedBefore(ctx context.Context, arg ListFollowingFeedBeforeParams) ([]ListFollowingFeedBeforeRow, error) {
	rows, err := q.db.QueryContext(ctx, listFollowingFeedBefore, arg.FollowerID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowingFeedBeforeRow{}
	for rows.Next() {
		var i ListFollowingFeedBeforeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Body,
			&i.PrefectureCode,
			&i.SpotName,
			&i.VisitedOn,
			&i.LikeCount,
			&i.CommentCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Handle,
			&i.DisplayName,
			&i.Bio,
			&i.PrefectureName,
			&i.PrefectureNameKana,
			&i.Region,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsBefore = `-- name: ListPostsBefore :many
SELECT
    p.id, p.user_id, p.body, p.prefecture_code, p.spot_name, p.visited_on,
    p.like_count, p.comment_count, p.created_at, p.updated_at,
    u.handle, u.display_name, u.bio,
    pref.name AS prefecture_name, pref.name_kana AS prefecture_name_kana, pref.region
FROM posts p
JOIN users u ON u.id = p.user_id
JOIN prefectures pref ON pref.code = p.prefecture_code
WHERE p.id < ?
ORDER BY p.id DESC
LIMIT ?
`

type ListPostsBeforeParams struct {
	ID    uint64
	Limit int32
}

type ListPostsBeforeRow struct {
	ID                 uint64
	UserID             uint64
	Body               string
	PrefectureCode     string
	SpotName           sql.NullString
	VisitedOn          time.Time
	LikeCount          uint32
	CommentCount       uint32
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Handle             string
	DisplayName        string
	Bio                sql.NullString
	PrefectureName     string
	PrefectureNameKana string
	Region             string
}

// 新着フィード。カーソルページネーション。
//
// **OFFSET は使わない。** 深いページでは読み飛ばす件数だけ処理が増える。
// 前回の最後の id より小さいものを取る形にすれば、常に一定の手数で済む。
//
// カーソルを id だけにできるのは、**created_at をデータベースが挿入時に
// 付けており、id（AUTO_INCREMENT）と同じ順序になる**ためである。
// アプリケーションから created_at を指定していたら、この前提は崩れる。
//
// 主キーの逆順走査になるため索引がそのまま効く。
func (q *Queries) ListPostsBefore(ctx context.Context, arg ListPostsBeforeParams) ([]ListPostsBeforeRow, error) {
	rows, err := q.db.QueryContext(ctx, listPostsBefore, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsBeforeRow{}
	for rows.Next() {
		var i ListPostsBeforeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Body,
			&i.PrefectureCode,
			&i.SpotName,
			&i.VisitedOn,
			&i.LikeCount,
			&i.CommentCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Handle,
			&i.DisplayName,
			&i.Bio,
			&i.PrefectureName,
			&i.PrefectureNameKana,
			&i.Region,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByUserBefore = `-- name: ListPostsByUserBefore :many
SELECT
    p.id, p.user_id, p.body, p.prefecture_code, p.spot_name, p.visited_on,
    p.like_count, p.comment_count, p.created_at, p.updated_at,
    u.handle, u.display_name, u.bio,
    pref.name AS prefecture_name, pref.name_kana AS prefecture_name_kana, pref.region
FROM posts p
JOIN users u ON u.id = p.user_id
JOIN prefectures pref ON pref.code = p.prefecture_code
WHERE p.user_id = ? AND p.id < ?
ORDER BY p.id DESC
LIMIT ?
`

type ListPostsByUserBeforeParams struct {
	UserID uint64
	ID     uint64
	Limit  int32
}

type ListPostsByUserBeforeRow struct {
	ID                 uint64
	UserID             uint64
	Body               string
	PrefectureCode     string
	SpotName           sql.NullString
	VisitedOn          time.Time
	LikeCount          uint32
	CommentCount       uint32
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Handle             string
	DisplayName        string
	Bio                sql.NullString
	PrefectureName     string
	PrefectureNameKana string
	Region             string
}

// ある利用者の投稿。新着フィードと同じくカーソルページネーション。
//
// 索引は ix_posts_user_id (user_id, id DESC)。
// **ix_posts_user_created (user_id, created_at DESC) では足りない。**
// 絞り込みには使えるが ORDER BY id DESC を索引の並びで解決できず、
// EXPLAIN に Using filesort が出る（2026-08-29 に実測して確認し、
// 000003 で索引を追加した）。投稿数の多い利用者ほど並べ替える行が増える。
func (q *Queries) ListPostsByUserBefore(ctx context.Context, arg ListPostsByUserBeforeParams) ([]ListPostsByUserBeforeRow, error) {
	rows, err := q.db.QueryContext(ctx, listPostsByUserBefore, arg.UserID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsByUserBeforeRow{}
	for rows.Next() {
		var i ListPostsByUserBeforeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Body,
			&i.PrefectureCode,
			&i.SpotName,
			&i.VisitedOn,
			&i.LikeCount,
			&i.CommentCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Handle,
			&i.DisplayName,
			&i.Bio,
			&i.PrefectureName,
			&i.PrefectureNameKana,
			&i.Region,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :exec
UPDATE posts
SET body = ?, prefecture_code = ?, spot_name = ?, visited_on = ?
WHERE id = ? AND user_id = ?
`

type UpdatePostParams struct {
	Body           string
	PrefectureCode string
	SpotName       sql.NullString
	VisitedOn      time.Time
	ID             uint64
	UserID         uint64
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) error {
	_, err := q.db.ExecContext(ctx, updatePost,
		arg.Body,
		arg.PrefectureCode,
		arg.SpotName,
		arg.VisitedOn,
		arg.ID,
		arg.UserID,
	)
	return err
}
