// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const createPost = `-- name: CreatePost :execresult

INSERT INTO posts (user_id, body, prefecture_code, spot_name, visited_on)
VALUES (?, ?, ?, ?, ?)
`

type CreatePostParams struct {
	UserID         uint64
	Body           string
	PrefectureCode string
	SpotName       sql.NullString
	VisitedOn      time.Time
}

// 投稿。
func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPost,
		arg.UserID,
		arg.Body,
		arg.PrefectureCode,
		arg.SpotName,
		arg.VisitedOn,
	)
}

const deletePost = `-- name: DeletePost :execresult
DELETE FROM posts
WHERE id = ? AND user_id = ?
`

type DeletePostParams struct {
	ID     uint64
	UserID uint64
}

func (q *Queries) DeletePost(ctx context.Context, arg DeletePostParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deletePost, arg.ID, arg.UserID)
}

const getPostByID = `-- name: GetPostByID :one
SELECT
    p.id, p.user_id, p.body, p.prefecture_code, p.spot_name, p.visited_on,
    p.like_count, p.comment_count, p.created_at, p.updated_at,
    u.handle, u.display_name, u.bio,
    pref.name AS prefecture_name, pref.name_kana AS prefecture_name_kana, pref.region
FROM posts p
JOIN users u ON u.id = p.user_id
JOIN prefectures pref ON pref.code = p.prefecture_code
WHERE p.id = ?
`

type GetPostByIDRow struct {
	ID                 uint64
	UserID             uint64
	Body               string
	PrefectureCode     string
	SpotName           sql.NullString
	VisitedOn          time.Time
	LikeCount          uint32
	CommentCount       uint32
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Handle             string
	DisplayName        string
	Bio                sql.NullString
	PrefectureName     string
	PrefectureNameKana string
	Region             string
}

func (q *Queries) GetPostByID(ctx context.Context, id uint64) (GetPostByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPostByID, id)
	var i GetPostByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Body,
		&i.PrefectureCode,
		&i.SpotName,
		&i.VisitedOn,
		&i.LikeCount,
		&i.CommentCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Handle,
		&i.DisplayName,
		&i.Bio,
		&i.PrefectureName,
		&i.PrefectureNameKana,
		&i.Region,
	)
	return i, err
}

const getPostOwner = `-- name: GetPostOwner :one
SELECT user_id FROM posts WHERE id = ?
`

// 投稿の所有者だけを取る。権限確認のために本体を全部読む必要はない。
func (q *Queries) GetPostOwner(ctx context.Context, id uint64) (uint64, error) {
	row := q.db.QueryRowContext(ctx, getPostOwner, id)
	var user_id uint64
	err := row.Scan(&user_id)
	return user_id, err
}

const updatePost = `-- name: UpdatePost :exec
UPDATE posts
SET body = ?, prefecture_code = ?, spot_name = ?, visited_on = ?
WHERE id = ? AND user_id = ?
`

type UpdatePostParams struct {
	Body           string
	PrefectureCode string
	SpotName       sql.NullString
	VisitedOn      time.Time
	ID             uint64
	UserID         uint64
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) error {
	_, err := q.db.ExecContext(ctx, updatePost,
		arg.Body,
		arg.PrefectureCode,
		arg.SpotName,
		arg.VisitedOn,
		arg.ID,
		arg.UserID,
	)
	return err
}
