// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prefectures.sql

package dbgen

import (
	"context"
)

const getPrefecture = `-- name: GetPrefecture :one
SELECT code, name, name_kana, region, sort_order
FROM prefectures
WHERE code = ?
`

func (q *Queries) GetPrefecture(ctx context.Context, code string) (Prefecture, error) {
	row := q.db.QueryRowContext(ctx, getPrefecture, code)
	var i Prefecture
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.NameKana,
		&i.Region,
		&i.SortOrder,
	)
	return i, err
}

const listPrefectures = `-- name: ListPrefectures :many

SELECT code, name, name_kana, region, sort_order
FROM prefectures
ORDER BY sort_order
`

// 都道府県マスタの参照。47件・不変のため参照系のみを置く。
func (q *Queries) ListPrefectures(ctx context.Context) ([]Prefecture, error) {
	rows, err := q.db.QueryContext(ctx, listPrefectures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Prefecture{}
	for rows.Next() {
		var i Prefecture
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.NameKana,
			&i.Region,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
