// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const createRefreshToken = `-- name: CreateRefreshToken :execresult

INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
VALUES (?, ?, ?)
`

type CreateRefreshTokenParams struct {
	UserID    uint64
	TokenHash string
	ExpiresAt time.Time
}

// リフレッシュトークン。保存しているのは SHA-256 ハッシュのみで、平文は持たない。
func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
}

const getRefreshTokenByHashForUpdate = `-- name: GetRefreshTokenByHashForUpdate :one
SELECT id, user_id, token_hash, expires_at, revoked_at, replaced_by, created_at
FROM refresh_tokens
WHERE token_hash = ?
FOR UPDATE
`

// ローテーションのために行を固定する。
//
// FOR UPDATE が要点である。これが無いと、同時に届いた2つのリフレッシュが
// 両方とも「まだ失効していない」と読み、どちらも正規のローテーションとして
// 通ってしまう。行ロックで直列化し、片方を必ず「失効済みの提示」側へ回す。
func (q *Queries) GetRefreshTokenByHashForUpdate(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenByHashForUpdate, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAllRefreshTokensForUser = `-- name: RevokeAllRefreshTokensForUser :exec
UPDATE refresh_tokens
SET revoked_at = ?
WHERE user_id = ? AND revoked_at IS NULL
`

type RevokeAllRefreshTokensForUserParams struct {
	RevokedAt sql.NullTime
	UserID    uint64
}

// 盗用を検知したときと、パスワード変更時に使う。
func (q *Queries) RevokeAllRefreshTokensForUser(ctx context.Context, arg RevokeAllRefreshTokensForUserParams) error {
	_, err := q.db.ExecContext(ctx, revokeAllRefreshTokensForUser, arg.RevokedAt, arg.UserID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = ?, replaced_by = ?
WHERE id = ? AND revoked_at IS NULL
`

type RevokeRefreshTokenParams struct {
	RevokedAt  sql.NullTime
	ReplacedBy sql.NullInt64
	ID         uint64
}

// 失効させ、後継を記録する。
//
// replaced_by は「正規のローテーションで置き換えられた」ことの根拠になる。
// これが無いと、タブを複数開いた利用者の同時リフレッシュを
// 盗用と誤判定して全ログアウトさせてしまう。
func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshToken, arg.RevokedAt, arg.ReplacedBy, arg.ID)
	return err
}

const revokeRefreshTokenByHash = `-- name: RevokeRefreshTokenByHash :exec
UPDATE refresh_tokens
SET revoked_at = ?
WHERE token_hash = ? AND revoked_at IS NULL
`

type RevokeRefreshTokenByHashParams struct {
	RevokedAt sql.NullTime
	TokenHash string
}

// ログアウト。冪等にするため、既に失効していてもエラーにしない。
func (q *Queries) RevokeRefreshTokenByHash(ctx context.Context, arg RevokeRefreshTokenByHashParams) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshTokenByHash, arg.RevokedAt, arg.TokenHash)
	return err
}
