// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package dbgen

import (
	"context"
	"database/sql"
)

const attachTagToPost = `-- name: AttachTagToPost :exec
INSERT INTO post_tags (post_id, tag_id) VALUES (?, ?)
ON DUPLICATE KEY UPDATE post_id = post_id
`

type AttachTagToPostParams struct {
	PostID uint64
	TagID  uint64
}

func (q *Queries) AttachTagToPost(ctx context.Context, arg AttachTagToPostParams) error {
	_, err := q.db.ExecContext(ctx, attachTagToPost, arg.PostID, arg.TagID)
	return err
}

const detachAllTagsFromPost = `-- name: DetachAllTagsFromPost :exec
DELETE FROM post_tags WHERE post_id = ?
`

func (q *Queries) DetachAllTagsFromPost(ctx context.Context, postID uint64) error {
	_, err := q.db.ExecContext(ctx, detachAllTagsFromPost, postID)
	return err
}

const listTagsByPostID = `-- name: ListTagsByPostID :many
SELECT t.name
FROM tags t
JOIN post_tags pt ON pt.tag_id = t.id
WHERE pt.post_id = ?
ORDER BY t.name
`

func (q *Queries) ListTagsByPostID(ctx context.Context, postID uint64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTagsByPostID, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTag = `-- name: UpsertTag :execresult

INSERT INTO tags (name) VALUES (?)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id)
`

// タグ。名前は正規化（前後空白除去・NFKC・小文字化）してから渡すこと。
// 既にあれば作らない。同時に同じタグが作られても一意制約で1つに収まる。
func (q *Queries) UpsertTag(ctx context.Context, name string) (sql.Result, error) {
	return q.db.ExecContext(ctx, upsertTag, name)
}
