/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * アカウントの作成
         * @description 作成と同時にログイン状態にする。アクセストークンを本文で返し、
         *     リフレッシュトークンを Cookie に設定する。
         *
         *     **メールアドレスの確認は行わない。** メール送信を対象外にしているため、
         *     存在しないアドレスでも登録できる（要件定義書 3.2 の割り切り）。
         */
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ログイン
         * @description **認証に失敗した理由を区別しない。** 「そのアドレスは登録されていない」と
         *     「パスワードが違う」を分けて返すと、どのアドレスが登録済みかを
         *     総当たりで調べられる。どちらも同じ `invalid_credentials` を返す。
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * アクセストークンの再発行
         * @description Cookie のリフレッシュトークンから新しいアクセストークンを発行し、
         *     **リフレッシュトークン自体もローテーションする**（新規発行＋旧失効）。
         *
         *     **失効済みトークンの再提示は盗用の兆候とみなし、そのユーザーの
         *     全トークンを失効させる。** ただし正規のローテーション直後の短い猶予時間内は
         *     例外とする。タブを複数開いた利用者の同時リフレッシュを
         *     誤って盗用と判定し、正常な利用者をログアウトさせないためである。
         *
         *     このエンドポイントは Cookie で認証するため CSRF の対象になる。
         *     `SameSite=Strict` に加えて `X-Requested-With: tabi-log` の付与を要求する。
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ログアウト
         * @description リフレッシュトークンを失効させ、Cookie を削除する。
         *
         *     **発行済みのアクセストークンは最大15分間有効なままである。**
         *     取り消すにはリクエストごとに失効一覧を参照する必要があり、
         *     JWT を使う意味が薄れるため行わない。仕様上の制約として受け入れている。
         *
         *     トークンが無い場合も 204 を返す（冪等）。
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ログイン中の利用者
         * @description アクセストークンが指す利用者を返す。画面の初期化に使う。
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/presign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 画像アップロード用の署名付きURLを発行する
         * @description 画像はブラウザから S3 へ直接送る。バックエンドを経由させないのは、
         *     大きなファイルでサーバーの帯域とタイムアウトがボトルネックになるのを
         *     避けるためである。
         *
         *     **署名付きURLを発行する時点で `media` を `pending` として記録する。**
         *     「アップロードされる予定」を先に永続化しておかないと、送信後に投稿が
         *     確定されなかった分だけ S3 に誰も参照しないオブジェクトが溜まり続け、
         *     後から特定する手立てが無くなる。
         *
         *     アップロード後、S3 のイベントで起動する処理が形式を検証し、
         *     **EXIF（GPS座標・撮影日時）を除去**して表示用の変換物を作る。
         *     その処理が完了して `processed` になった画像だけが投稿に使える。
         *
         *     署名には Content-Type と最大サイズが焼き込まれる。条件に合わない
         *     アップロードは S3 側で拒否される。
         */
        post: operations["presignMediaUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{mediaId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 画像の処理状況
         * @description アップロードした画像の処理が終わったかを返す。
         *
         *     **S3 への送信が終わっても、すぐには投稿に使えない。** 形式の検証・
         *     EXIF の除去・表示用の変換が終わって `processed` になる必要がある。
         *     その処理は S3 のイベントで非同期に走るため、**クライアントは
         *     完了を知る手段を持たない**。この経路がその手段になる。
         *
         *     これが無いと、画面は「送信が終わった」時点で投稿できると誤解し、
         *     サーバーに拒否されて初めて分かることになる。
         *
         *     自分がアップロードした画像のみ参照できる。
         */
        get: operations["getMediaStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feed/following": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * フォロー中フィード
         * @description **自分がフォローしている利用者**の投稿を投稿日の新しい順に返す。
         *     カーソルの扱いは新着フィードと同じ。
         *
         *     **自分の投稿は含まない。** 自分自身はフォローできないため、
         *     「フォローしている人の投稿」に自分は入らない。
         *     自分の投稿はプロフィールで見る。
         *
         *     > **ここは負荷試験の対象である。** 想定は1人あたり平均200フォロー。
         *     > 絞り込みの元が `follows` の走査になるため、フォロー数が増えると
         *     > 1ページ返すのに読む行が増える。実測して必要なら作り方を変える。
         */
        get: operations["listFollowingFeed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{handle}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 利用者のハンドル。英数字とアンダースコアのみ */
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        /**
         * プロフィールを取得する
         * @description ハンドルで引く。**id ではなくハンドルを URL に使う。**
         *     利用者が人に伝えられる識別子であり、`/users/traveler_01` のほうが
         *     `/users/42` より意味が伝わるためである。
         *
         *     投稿数・フォロー数・フォロワー数は集計で求める。カウンタ列にしていないのは、
         *     **プロフィールは1画面につき1回しか開かれず、フィードのように
         *     20件分を繰り返し引く経路が無い**ためである。いいね数とは事情が違う。
         */
        get: operations["getUserProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{handle}/follow": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 利用者のハンドル。英数字とアンダースコアのみ */
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * フォローする
         * @description **冪等である。** 既にフォローしていても 204 を返す。
         *     いいねと同じ理由で PUT にしている（「この相手へのフォローを、有る状態にする」）。
         *
         *     **自分自身はフォローできない**（400）。DB の CHECK 制約でも防いでいるが、
         *     制約違反が 500 になるのを避けるためアプリケーション側でも判定する。
         *
         *     フォローされた相手に通知を作る。作成はフォローの登録と同一トランザクションで行う。
         */
        put: operations["followUser"];
        post?: never;
        /**
         * フォローを解除する
         * @description **冪等である。** フォローしていなくても 204 を返す。
         *
         *     解除すると、対応する通知も削除する。
         */
        delete: operations["unfollowUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{handle}/posts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 利用者のハンドル。英数字とアンダースコアのみ */
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        /**
         * その利用者の投稿
         * @description 投稿日の新しい順に返す。カーソルの扱いは新着フィードと同じ。
         *
         *     **訪問日順の「旅行履歴」は別の並びであり、ここには含めない。**
         *     時間軸が2つあることを画面の切り替えで表す（features.md 1.3）。
         */
        get: operations["listUserPosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{handle}/followers": {
        parameters: {
            query?: {
                /** @description 前回の応答の `nextCursor` */
                cursor?: components["parameters"]["UserCursor"];
                limit?: components["parameters"]["UserLimit"];
            };
            header?: never;
            path: {
                /** @description 利用者のハンドル。英数字とアンダースコアのみ */
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        /**
         * フォロワーの一覧
         * @description その利用者をフォローしている人を返す。
         *
         *     **並びは利用者 id の昇順であり、フォローした順ではない。**
         *     `follows` の索引が `(followee_id, follower_id)` であり、
         *     この順でのみカーソルが索引で解決できるためである。
         *     フォロー日時順にするには索引の追加が要る。
         */
        get: operations["listFollowers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{handle}/following": {
        parameters: {
            query?: {
                /** @description 前回の応答の `nextCursor` */
                cursor?: components["parameters"]["UserCursor"];
                limit?: components["parameters"]["UserLimit"];
            };
            header?: never;
            path: {
                /** @description 利用者のハンドル。英数字とアンダースコアのみ */
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        /**
         * フォロー中の一覧
         * @description その利用者がフォローしている人を返す。並びは `listFollowers` と同じ理由で
         *     利用者 id の昇順である。
         */
        get: operations["listFollowing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 新着フィード
         * @description 全利用者の投稿を投稿日の新しい順に返す。
         *
         *     **カーソルページネーションを使う。** `OFFSET` は深いページで
         *     件数分を読み飛ばすため劣化する。前回の最後の投稿を指す `cursor` を
         *     渡すと、その続きから返す。
         *
         *     並び順は**投稿日**であり訪問日ではない。旅行から帰ったあとに
         *     まとめて投稿するのが自然な使われ方であり、フィードは
         *     「新しく共有されたもの」を見せる場だからである。
         *     訪問日順で見せるのはプロフィールの旅行履歴の役割になる。
         */
        get: operations["listPosts"];
        put?: never;
        /**
         * 投稿を作成する
         * @description 画像・本文・都道府県・訪問日・タグをまとめて確定する。
         *
         *     **投稿本体・画像の紐づけ・タグの登録を1つのトランザクションで行う。**
         *     分かれていると、途中で失敗したときに「画像の無い投稿」や
         *     「どの投稿にも属さない画像」が残る。
         *
         *     指定できる画像は、**自分がアップロードし、処理が完了しており
         *     （`processed`）、まだどの投稿にも紐づいていないもの**に限る。
         */
        post: operations["createPost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{postId}/likes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * いいねする
         * @description **冪等である。** 既にいいねしていても 204 を返す。
         *     POST ではなく PUT にしているのはそのためで、
         *     「この投稿に対する自分のいいねを、有る状態にする」という意味になる。
         *
         *     二重のいいねは複合主キー `(user_id, post_id)` が防ぐ。
         *
         *     **`posts.like_count` の増減をいいねの登録と同一トランザクションで行う。**
         *     フィードは1画面で20件返すため、都度 `COUNT` を撃つと20件それぞれに
         *     集計が走る（N+1 の温床）。カウンタ列にする代わりに、
         *     整合性はトランザクションで担保する。
         *
         *     自分の投稿にもいいねできる。ただし**自分への通知は作らない**。
         */
        put: operations["likePost"];
        post?: never;
        /**
         * いいねを取り消す
         * @description **冪等である。** いいねしていなくても 204 を返す。
         *
         *     取り消すと、対応する通知も削除する。
         */
        delete: operations["unlikePost"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{postId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        /**
         * コメントの一覧
         * @description 古い順に返す。会話は上から読むものであり、フィードのように
         *     新しいものから見るのは適さないためである。
         *
         *     **返信ツリーは作らない**（要件定義書 3.2 の対象外）。1階層に固定する。
         */
        get: operations["listComments"];
        put?: never;
        /**
         * コメントする
         * @description **`posts.comment_count` の増減をコメントの登録と同一トランザクションで行う。**
         *
         *     自分の投稿にもコメントできる。ただし**自分への通知は作らない**。
         */
        post: operations["createComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comments/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * コメントを削除する
         * @description 削除できるのは**コメントを書いた本人と、投稿の作成者**の両方である。
         *
         *     投稿者に削除させないと、自分の投稿に付いた不快なコメントを消す手段が
         *     「投稿ごと消す」しか無くなる。
         */
        delete: operations["deleteComment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{postId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        /** 投稿を取得する */
        get: operations["getPost"];
        put?: never;
        post?: never;
        /**
         * 投稿を削除する
         * @description コメント・いいね・タグの紐づけ・画像が連鎖して削除される。
         *     S3 上のオブジェクトはデータベースの制約では消えないため、
         *     アプリケーションから明示的に削除する。
         */
        delete: operations["deletePost"];
        options?: never;
        head?: never;
        /**
         * 投稿を編集する
         * @description **画像の差し替えは対象外**（要件定義書 3.2）。本文・都道府県・
         *     スポット名・訪問日・タグ・代替テキストを変更できる。
         *
         *     **自分の投稿であることをサーバー側で検証する。**
         *     画面側の制御は操作性のためであり、権限の根拠にはしない。
         */
        patch: operations["updatePost"];
        trace?: never;
    };
    "/prefectures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 都道府県マスタの一覧
         * @description 47件を JIS X 0401 のコード順で返す。投稿フォームの選択肢と、
         *     都道府県制覇マップの土台に使う。
         *
         *     **認証を要さない。** 総務省が定める公開情報であり、
         *     利用者ごとに内容が変わらないためである。
         *     （アプリの他の画面は認証を要する。[要件定義書](requirements.md) 2 章）
         *
         *     内容は不変なので、クライアントは長期間キャッシュしてよい。
         */
        get: operations["listPrefectures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/livez": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * プロセスの生存確認
         * @description **依存先を一切見ない。** ロードバランサのヘルスチェックはこちらへ向ける。
         *
         *     依存先まで確認するヘルスチェックをロードバランサに向けると、
         *     データベースが一時的に不調になったときに全タスクが同時に unhealthy と
         *     判定されて一斉に置き換えられる。置き換えてもデータベースは回復しないため
         *     状況が悪化するだけである。タスクを入れ替えるべき理由になるのは
         *     「プロセスが生きていないこと」だけである。
         */
        get: operations["getLivez"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 依存先を含む疎通確認
         * @description データベースへの疎通を含めて確認する。デプロイ時の投入判定や
         *     運用中の状況確認に使う。**ロードバランサのヘルスチェックには使わない。**
         */
        get: operations["getReadyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: {
                /**
                 * @description 機械可読な識別子。**クライアントはこちらで分岐すること。**
                 *     message は表示専用であり、文言の変更で分岐が壊れないようにする。
                 * @example dependency_unavailable
                 */
                code: string;
                /**
                 * @description 利用者に表示する説明。内部構造やスタックは含めない。
                 * @example データベースへ接続できません
                 */
                message: string;
            };
        };
        SignupRequest: {
            /**
             * @description メールアドレス。ログインIDとして使う
             * @example traveler@example.com
             */
            email: string;
            /**
             * @description URL に使う識別子。英数字とアンダースコアのみ
             * @example traveler_01
             */
            handle: string;
            /** @example たびびと */
            displayName: string;
            /**
             * Format: password
             * @description 8文字以上。**上限を 72 にしているのは bcrypt の制約**である。
             *     bcrypt は 72 バイトを超える入力を切り捨てるため、
             *     それ以上を受け付けると「長いほど安全」という利用者の期待を裏切る。
             */
            password: string;
        };
        LoginRequest: {
            /** @description メールアドレス */
            email: string;
            /** Format: password */
            password: string;
        };
        AuthResponse: {
            data: {
                /**
                 * @description JWT。`Authorization: Bearer <token>` で送る。
                 *
                 *     **クライアントはこれをメモリにのみ保持し、localStorage に
                 *     保存しない。** 保存すると XSS で読み出せてしまう。
                 *     リロード時は `/auth/refresh` から取り直す。
                 */
                accessToken: string;
                /**
                 * @description アクセストークンの残り有効秒数
                 * @example 900
                 */
                expiresIn: number;
                user: components["schemas"]["User"];
            };
        };
        MeResponse: {
            data: components["schemas"]["User"];
        };
        /** @description 公開してよい利用者情報のみを含む。メールアドレスは含めない */
        User: {
            /**
             * Format: int64
             * @example 1
             */
            id: number;
            /** @example traveler_01 */
            handle: string;
            /** @example たびびと */
            displayName: string;
            bio?: string | null;
        };
        /** @description 一覧に並べる利用者。フォローの導線を出すための状態を含む */
        UserSummary: {
            /** Format: int64 */
            id: number;
            handle: string;
            displayName: string;
            bio?: string | null;
            /** @description 閲覧者がこの利用者をフォローしているか */
            isFollowing: boolean;
            /** @description 閲覧者自身か。自分にフォローの導線を出さないために使う */
            isMe: boolean;
        };
        UserProfile: {
            /** Format: int64 */
            id: number;
            handle: string;
            displayName: string;
            bio?: string | null;
            postCount: number;
            followingCount: number;
            followerCount: number;
            /**
             * @description 投稿した都道府県の種類数。制覇率は 47 で割って画面が求める。
             *     **地図そのものは 8 章で作る。** ここでは数だけを返す。
             */
            visitedPrefectureCount: number;
            isFollowing: boolean;
            isMe: boolean;
        };
        UserProfileResponse: {
            data: components["schemas"]["UserProfile"];
        };
        UserListResponse: {
            data: {
                users: components["schemas"]["UserSummary"][];
                /** @description 続きがある場合のみ入る */
                nextCursor?: string | null;
            };
        };
        PresignRequest: {
            /**
             * @description 画像の種類。**この値は署名に焼き込まれる**ため、
             *     異なる種類でアップロードすると S3 が拒否する。
             *
             *     ただし申告値を信用はしない。アップロード後に
             *     マジックバイトで実際の形式を検証する。
             * @enum {string}
             */
            contentType: "image/jpeg" | "image/png" | "image/webp";
            /**
             * Format: int64
             * @description バイト数。上限も署名に焼き込まれる
             */
            contentLength: number;
        };
        PresignResponse: {
            data: {
                /**
                 * Format: int64
                 * @description 投稿を作成するときにこの ID を指定する
                 */
                mediaId: number;
                /** @description この URL へ PUT する。**サーバーを経由しない** */
                uploadUrl: string;
                /** @description 署名の有効秒数 */
                expiresIn: number;
            };
        };
        CreatePostRequest: {
            body: string;
            /** @description JIS X 0401 の都道府県コード。**必須**。自由入力は受け付けない */
            prefectureCode: string;
            /** @description 「道の駅○○」など。全文検索の対象に含める */
            spotName?: string | null;
            /**
             * Format: date
             * @description 訪問日。**投稿日とは別の軸である。** 旅行から帰ったあとに
             *     まとめて投稿するのが自然な使われ方のため。未来日は受け付けない。
             */
            visitedOn: string;
            tags?: string[];
            media: components["schemas"]["PostMediaInput"][];
        };
        /** @description 画像の差し替えはできない。代替テキストのみ変更できる */
        UpdatePostRequest: {
            body: string;
            prefectureCode: string;
            spotName?: string | null;
            /** Format: date */
            visitedOn: string;
            tags?: string[];
            /** @description 既にこの投稿に紐づいている画像の代替テキスト */
            mediaAltTexts: components["schemas"]["MediaAltText"][];
        };
        PostMediaInput: {
            /** Format: int64 */
            mediaId: number;
            /**
             * @description **必須。** 写真が主役のサービスで代替テキストを任意にすると
             *     実質的に入力されず、画像が見えない利用者に何も伝わらなくなる。
             */
            altText: string;
        };
        MediaAltText: {
            /** Format: int64 */
            mediaId: number;
            altText: string;
        };
        MediaStatusResponse: {
            data: {
                /** Format: int64 */
                mediaId: number;
                /**
                 * @description `pending`   … 署名付きURLを発行したが、まだ届いていない
                 *     `uploaded`  … 届いたが処理中
                 *     `processed` … **投稿に使える**
                 *     `failed`    … 画像として扱えなかった。投稿には使えない
                 * @enum {string}
                 */
                status: "pending" | "uploaded" | "processed" | "failed";
            };
        };
        PostResponse: {
            data: components["schemas"]["Post"];
        };
        CreateCommentRequest: {
            body: string;
        };
        CommentResponse: {
            data: components["schemas"]["Comment"];
        };
        CommentListResponse: {
            data: {
                comments: components["schemas"]["Comment"][];
                /** @description 次のページを取るときに `cursor` として渡す。これ以上無い場合は null */
                nextCursor?: string | null;
            };
        };
        Comment: {
            /** Format: int64 */
            id: number;
            author: components["schemas"]["User"];
            body: string;
            /** Format: date-time */
            createdAt: string;
            /**
             * @description このコメントを削除できるか。**表示の出し分けのためだけに使う。**
             *
             *     権限そのものはサーバー側で判定しており、この値を書き換えても
             *     削除はできない。画面がボタンを出すかどうかを決めるための情報である。
             */
            canDelete: boolean;
        };
        PostListResponse: {
            data: {
                posts: components["schemas"]["Post"][];
                /**
                 * @description 次のページを取るときに `cursor` として渡す。
                 *     **これ以上無い場合は null になる。** 空文字ではなく null に
                 *     しているのは、「続きがない」ことを呼び出し側が
                 *     真偽で判定できるようにするためである。
                 */
                nextCursor?: string | null;
            };
        };
        Post: {
            /** Format: int64 */
            id: number;
            author: components["schemas"]["User"];
            body: string;
            prefecture: components["schemas"]["Prefecture"];
            spotName?: string | null;
            /** Format: date */
            visitedOn: string;
            media: components["schemas"]["Media"][];
            tags: string[];
            likeCount: number;
            commentCount: number;
            /**
             * @description **この投稿に自分がいいねしているか。**
             *
             *     フィードでは表示する20件それぞれについて必要になる。
             *     投稿ごとに問い合わせると N+1 になるため、
             *     `likes` の主キーを `(user_id, post_id)` の順にしてあり、
             *     `WHERE user_id = ? AND post_id IN (...)` の1クエリで解決する。
             */
            isLiked: boolean;
            /**
             * @description この投稿を削除できるか。**表示の出し分けのためだけに使う。**
             *     権限はサーバー側で判定しており、この値を書き換えても削除はできない。
             */
            canDelete: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        Media: {
            /** Format: int64 */
            id: number;
            altText: string;
            width: number;
            height: number;
            /** @description 長辺320px。一覧で使う */
            thumbUrl: string;
            /** @description 長辺1080px。詳細で使う */
            mediumUrl: string;
        };
        Prefecture: {
            /**
             * @description JIS X 0401 の都道府県コード。`01`〜`47` の2桁（先頭のゼロを含む）
             * @example 01
             */
            code: string;
            /** @example 北海道 */
            name: string;
            /**
             * @description 読み。並べ替えと検索の補助に使う
             * @example ほっかいどう
             */
            nameKana: string;
            /**
             * @description 八地方区分。「関東の投稿」のような粒度での絞り込みに使う
             * @example 北海道
             * @enum {string}
             */
            region: "北海道" | "東北" | "関東" | "中部" | "近畿" | "中国" | "四国" | "九州沖縄";
        };
        PrefectureListResponse: {
            /** @description JIS コード順に並んだ47件 */
            data: components["schemas"]["Prefecture"][];
        };
        LivezResponse: {
            data: {
                /** @enum {string} */
                status: "ok";
            };
        };
        ReadyzResponse: {
            data: {
                /** @enum {string} */
                status: "ok";
                /** @enum {string} */
                database: "ok";
            };
        };
    };
    responses: {
        /** @description 入力が要件を満たしていない */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description アクセストークンが無い、期限切れ、または不正である */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description CSRF 対策のヘッダーが無い、または値が正しくない */
        CsrfRejected: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 試行回数の上限に達した */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 対象が存在しない */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 権限が無い（他人の投稿を操作しようとした等） */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description 利用者のハンドル。英数字とアンダースコアのみ */
        Handle: string;
        /** @description 前回の応答の `nextCursor` */
        UserCursor: string;
        UserLimit: number;
        PostId: number;
        /**
         * @description CSRF 対策。値は `tabi-log` 固定。
         *
         *     カスタムヘッダーは単純リクエストの条件を外れるため、
         *     クロスオリジンから送るには CORS のプリフライトが通る必要がある。
         *     フォーム送信や `<img>` のような**プリフライトを伴わない経路では付けられない**。
         *     `SameSite=Strict` と合わせて二重に守る。
         */
        RequestedWith: "tabi-log";
    };
    requestBodies: never;
    headers: {
        /**
         * @description リフレッシュトークンを設定する `Set-Cookie`。
         *
         *     `HttpOnly` `Secure` `SameSite=Strict` を付け、
         *     **`Path=/api/auth` に限定する**。投稿や検索といった他の API リクエストには
         *     一切乗らないため、Cookie が晒される面が小さくなる。
         *
         *     `/api/auth/refresh` まで絞らないのは、**ログアウトでも Cookie を読んで
         *     サーバー側で失効させる必要がある**ためである。より狭い Path にすると
         *     `/api/auth/logout` へ Cookie が送られず、ブラウザ側で消すことしかできない。
         */
        RefreshTokenCookie: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description 作成した */
            201: {
                headers: {
                    "Set-Cookie": components["headers"]["RefreshTokenCookie"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            /** @description メールアドレスかハンドルが既に使われている */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description ログインした */
            200: {
                headers: {
                    "Set-Cookie": components["headers"]["RefreshTokenCookie"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            /** @description メールアドレスかパスワードが正しくない */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description CSRF 対策。値は `tabi-log` 固定。
                 *
                 *     カスタムヘッダーは単純リクエストの条件を外れるため、
                 *     クロスオリジンから送るには CORS のプリフライトが通る必要がある。
                 *     フォーム送信や `<img>` のような**プリフライトを伴わない経路では付けられない**。
                 *     `SameSite=Strict` と合わせて二重に守る。
                 */
                "X-Requested-With": components["parameters"]["RequestedWith"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 再発行した */
            200: {
                headers: {
                    "Set-Cookie": components["headers"]["RefreshTokenCookie"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /**
             * @description リフレッシュトークンが無い・期限切れ・失効済みである。
             *     `code` が `token_reuse_detected` の場合は盗用とみなして
             *     全トークンを失効させており、再ログインが必要になる。
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: components["responses"]["CsrfRejected"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description CSRF 対策。値は `tabi-log` 固定。
                 *
                 *     カスタムヘッダーは単純リクエストの条件を外れるため、
                 *     クロスオリジンから送るには CORS のプリフライトが通る必要がある。
                 *     フォーム送信や `<img>` のような**プリフライトを伴わない経路では付けられない**。
                 *     `SameSite=Strict` と合わせて二重に守る。
                 */
                "X-Requested-With": components["parameters"]["RequestedWith"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ログアウトした（トークンが無い場合も含む） */
            204: {
                headers: {
                    /** @description リフレッシュトークンを削除する `Set-Cookie` */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["CsrfRejected"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ログイン中の利用者 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    presignMediaUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresignRequest"];
            };
        };
        responses: {
            /** @description 発行した */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresignResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    getMediaStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mediaId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 処理状況 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaStatusResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listFollowingFeed: {
        parameters: {
            query?: {
                /** @description 前回の応答の `nextCursor` */
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 投稿の一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostListResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    getUserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 利用者のハンドル。英数字とアンダースコアのみ */
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description プロフィール */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    followUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 利用者のハンドル。英数字とアンダースコアのみ */
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description フォローした（既にしていた場合も含む） */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    unfollowUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 利用者のハンドル。英数字とアンダースコアのみ */
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 解除した（していなかった場合も含む） */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    listUserPosts: {
        parameters: {
            query?: {
                /** @description 前回の応答の `nextCursor` */
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                /** @description 利用者のハンドル。英数字とアンダースコアのみ */
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 投稿の一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostListResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    listFollowers: {
        parameters: {
            query?: {
                /** @description 前回の応答の `nextCursor` */
                cursor?: components["parameters"]["UserCursor"];
                limit?: components["parameters"]["UserLimit"];
            };
            header?: never;
            path: {
                /** @description 利用者のハンドル。英数字とアンダースコアのみ */
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 利用者の一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    listFollowing: {
        parameters: {
            query?: {
                /** @description 前回の応答の `nextCursor` */
                cursor?: components["parameters"]["UserCursor"];
                limit?: components["parameters"]["UserLimit"];
            };
            header?: never;
            path: {
                /** @description 利用者のハンドル。英数字とアンダースコアのみ */
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 利用者の一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    listPosts: {
        parameters: {
            query?: {
                /** @description 前回の応答の `nextCursor`。省略すると先頭から返す */
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 投稿の一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostListResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    createPost: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePostRequest"];
            };
        };
        responses: {
            /** @description 作成した */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    likePost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description いいねした（既にしていた場合も含む） */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    unlikePost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 取り消した（していなかった場合も含む） */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    listComments: {
        parameters: {
            query?: {
                /** @description 前回の応答の `nextCursor` */
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                postId: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description コメントの一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentListResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    createComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommentRequest"];
            };
        };
        responses: {
            /** @description 作成した */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 削除した */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 投稿 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    deletePost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 削除した */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updatePost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePostRequest"];
            };
        };
        responses: {
            /** @description 更新した */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listPrefectures: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 47件の都道府県 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrefectureListResponse"];
                };
            };
        };
    };
    getLivez: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description プロセスは動作している */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivezResponse"];
                };
            };
        };
    };
    getReadyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description すべての依存先へ疎通できる */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyzResponse"];
                };
            };
            /** @description いずれかの依存先へ疎通できない */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
