/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/prefectures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 都道府県マスタの一覧
         * @description 47件を JIS X 0401 のコード順で返す。投稿フォームの選択肢と、
         *     都道府県制覇マップの土台に使う。
         *
         *     **認証を要さない。** 総務省が定める公開情報であり、
         *     利用者ごとに内容が変わらないためである。
         *     （アプリの他の画面は認証を要する。[要件定義書](requirements.md) 2 章）
         *
         *     内容は不変なので、クライアントは長期間キャッシュしてよい。
         */
        get: operations["listPrefectures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/livez": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * プロセスの生存確認
         * @description **依存先を一切見ない。** ロードバランサのヘルスチェックはこちらへ向ける。
         *
         *     依存先まで確認するヘルスチェックをロードバランサに向けると、
         *     データベースが一時的に不調になったときに全タスクが同時に unhealthy と
         *     判定されて一斉に置き換えられる。置き換えてもデータベースは回復しないため
         *     状況が悪化するだけである。タスクを入れ替えるべき理由になるのは
         *     「プロセスが生きていないこと」だけである。
         */
        get: operations["getLivez"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 依存先を含む疎通確認
         * @description データベースへの疎通を含めて確認する。デプロイ時の投入判定や
         *     運用中の状況確認に使う。**ロードバランサのヘルスチェックには使わない。**
         */
        get: operations["getReadyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: {
                /**
                 * @description 機械可読な識別子。**クライアントはこちらで分岐すること。**
                 *     message は表示専用であり、文言の変更で分岐が壊れないようにする。
                 * @example dependency_unavailable
                 */
                code: string;
                /**
                 * @description 利用者に表示する説明。内部構造やスタックは含めない。
                 * @example データベースへ接続できません
                 */
                message: string;
            };
        };
        Prefecture: {
            /**
             * @description JIS X 0401 の都道府県コード。`01`〜`47` の2桁（先頭のゼロを含む）
             * @example 01
             */
            code: string;
            /** @example 北海道 */
            name: string;
            /**
             * @description 読み。並べ替えと検索の補助に使う
             * @example ほっかいどう
             */
            nameKana: string;
            /**
             * @description 八地方区分。「関東の投稿」のような粒度での絞り込みに使う
             * @example 北海道
             * @enum {string}
             */
            region: "北海道" | "東北" | "関東" | "中部" | "近畿" | "中国" | "四国" | "九州沖縄";
        };
        PrefectureListResponse: {
            /** @description JIS コード順に並んだ47件 */
            data: components["schemas"]["Prefecture"][];
        };
        LivezResponse: {
            data: {
                /** @enum {string} */
                status: "ok";
            };
        };
        ReadyzResponse: {
            data: {
                /** @enum {string} */
                status: "ok";
                /** @enum {string} */
                database: "ok";
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listPrefectures: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 47件の都道府県 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrefectureListResponse"];
                };
            };
        };
    };
    getLivez: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description プロセスは動作している */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivezResponse"];
                };
            };
        };
    };
    getReadyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description すべての依存先へ疎通できる */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyzResponse"];
                };
            };
            /** @description いずれかの依存先へ疎通できない */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
